services:
  backend:
    build: ./backend/golang
    ports:
      - "8080:8080"

  db:
    image: "postgres:16-alpine"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "password"
